### ISSUE TITLE
Ugly Mugs case study

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/case-studies#9]
See the [outline](https://github.com/foundersandcoders/case-studies). Also see e.g. https://github.com/foundersandcoders/case-studies/blob/master/breathewithme.md

**Comment by sofer** [comment]
@g-sam @matthewglover I know it's been a while, but I am very keen to get a case study for Ugly Mugs. Any chance you could put something together for us?

**Comment by g-sam** [comment]
See #10!
